# Generated by Django 2.1 on 2019-08-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, unique=True)),
                ('upwd', models.CharField(max_length=40)),
                ('uemail', models.EmailField(max_length=254, unique=True)),
                ('uaddress', models.CharField(default='', max_length=100)),
                ('uphone', models.CharField(default='', max_length=11)),
                ('ushou', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
