# Generated by Django 2.1 on 2019-08-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='odate',
            field=models.DateTimeField(auto_now=True, verbose_name='订单创建时间'),
        ),
    ]
